import {ServiceModel} from './models/service.model';

export const SERVICES = [
    {
        id: 1,
        img: '../assets/catering1',
        name: '1st Service',
        category: 'Catering',
        location: 'In Bern',
        price: '5000',
        maxPeople: '250',
        description: 'This is a very long string describing the service 1',
        street: 'mock-street',
        city: 'mock-city',
        zip: '0001',
        email: 'test1@mail.ch',
        phone: '012 345 67 89'
    },
    {
        id: 2,
        img: '../assets/catering2',
        name: '2nd Service',
        category: 'Catering',
        location: 'In Bern',
        price: '5000',
        maxPeople: '250',
        description: 'This is a very long string describing the service 2',
        street: 'mock-street',
        city: 'mock-city',
        zip: '0002',
        email: 'test2@mail.ch',
        phone: '012 345 67 89'
    },
    {
        id: 3,
        img: '../assets/location1',
        name: '3rd Service',
        category: 'Location',
        location: 'In Bern',
        price: '5000',
        maxPeople: '250',
        description: 'This is a very long string describing the service 3',
        street: 'mock-street',
        city: 'mock-city',
        zip: '0003',
        email: 'test3@mail.ch',
        phone: '012 345 67 89'
    },
    {
        id: 4,
        img: '../assets/location2',
        name: '4th Service',
        category: 'Location',
        location: 'In Bern',
        price: '5000',
        maxPeople: '250',
        description: 'This is a very long string describing the service 4',
        street: 'mock-street',
        city: 'mock-city',
        zip: '0004',
        email: 'test4@mail.ch',
        phone: '012 345 67 89'
    },
    {
        id: 5,
        img: '../assets/entertainment1',
        name: '5th Service',
        category: 'Entertainment',
        location: 'In Bern',
        price: '5000',
        maxPeople: '250',
        description: 'This is a very long string describing the service 5',
        street: 'mock-street',
        city: 'mock-city',
        zip: '0005',
        email: 'test5@mail.ch',
        phone: '012 345 67 89'
    },
    {
        id: 6,
        img: '../assets/entertainment2',
        name: '6th Service',
        category: 'Entertainment',
        location: 'In Bern',
        price: '5000',
        maxPeople: '250',
        description: 'This is a very long string describing the service 6',
        street: 'mock-street',
        city: 'mock-city',
        zip: '0006',
        email: 'test6@mail.ch',
        phone: '012 345 67 89'
    },
    {
        id: 7,
        img: '../assets/security1',
        name: '7th Service',
        category: 'Security',
        location: 'In Bern',
        price: '5000',
        maxPeople: '250',
        description: 'This is a very long string describing the service 7',
        street: 'mock-street',
        city: 'mock-city',
        zip: '0007',
        email: 'test7@mail.ch',
        phone: '012 345 67 89'
    },
    {
        id: 8,
        img: '../assets/security2',
        name: '8th Service',
        category: 'Security',
        location: 'In Bern',
        price: '5000',
        maxPeople: '250',
        description: 'This is a very long string describing the service',
        street: 'mock-street',
        city: 'mock-city',
        zip: '0000',
        email: 'test@mail.ch',
        phone: '012 345 67 89'
    },
];
